import '../models/app_notification.dart';
import '../models/app_role.dart';
import '../models/app_user.dart';
import '../models/booking.dart';
import '../models/car.dart';
import '../models/geo_point.dart';

class DemoSeedData {
  const DemoSeedData._();

  static List<AppUser> users() {
    return [
      AppUser(
        id: 'user-1',
        name: 'Aruzhan S.',
        email: 'user@demo.app',
        phone: '+7 700 000 0001',
        role: AppRole.user,
        licenseNumber: 'KZ-USER-001',
        photoUrl:
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 1, 15),
      ),
      AppUser(
        id: 'admin-1',
        name: 'Fleet Admin',
        email: 'admin@demo.app',
        phone: '+7 700 000 0002',
        role: AppRole.admin,
        licenseNumber: 'KZ-ADMIN-001',
        photoUrl:
            'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 1, 10),
      ),
      AppUser(
        id: 'user-2',
        name: 'Nikita P.',
        email: 'nikita@demo.app',
        phone: '+7 700 000 0003',
        role: AppRole.user,
        licenseNumber: 'KZ-USER-002',
        photoUrl:
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 2, 3),
        isBlocked: true,
      ),
    ];
  }

  static List<Car> cars() {
    return const [
      Car(
        id: 'car-1',
        brand: 'Tesla',
        model: 'Model 3',
        year: 2023,
        type: 'Sedan',
        category: 'Electric',
        pricePerHour: 8500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2389, lng: 76.8897),
        imageUrl: '',
        batteryLevel: 86,
        rangeKm: 410,
        seats: 5,
        transmission: 'Automatic',
        color: 'Pearl White',
        description: 'Premium electric sedan for city and business rentals.',
        features: ['Autopilot', 'Panoramic roof', 'Fast charging', 'Premium audio'],
      ),
      Car(
        id: 'car-2',
        brand: 'Hyundai',
        model: 'Sonata',
        year: 2022,
        type: 'Business',
        category: 'Business',
        pricePerHour: 7000,
        status: CarStatus.booked,
        location: GeoPoint(lat: 43.2510, lng: 76.9280),
        imageUrl: '',
        batteryLevel: 64,
        rangeKm: 540,
        seats: 5,
        transmission: 'Automatic',
        color: 'Black',
        description: 'Comfortable business-class sedan for long urban trips.',
        features: ['Climate control', 'Leather seats', 'Rear camera'],
      ),
      Car(
        id: 'car-3',
        brand: 'Toyota',
        model: 'RAV4',
        year: 2024,
        type: 'SUV',
        category: 'Family',
        pricePerHour: 9200,
        status: CarStatus.inUse,
        location: GeoPoint(lat: 43.2220, lng: 76.8510),
        imageUrl: '',
        batteryLevel: 73,
        rangeKm: 480,
        seats: 5,
        transmission: 'Automatic',
        color: 'Silver',
        description: 'Reliable SUV for family travel and regional routes.',
        features: ['AWD', 'Spacious trunk', 'Adaptive cruise'],
      ),
      Car(
        id: 'car-4',
        brand: 'Kia',
        model: 'K5',
        year: 2021,
        type: 'Comfort',
        category: 'Comfort',
        pricePerHour: 6200,
        status: CarStatus.maintenance,
        location: GeoPoint(lat: 43.2650, lng: 76.9450),
        imageUrl: '',
        batteryLevel: 51,
        rangeKm: 450,
        seats: 5,
        transmission: 'Automatic',
        color: 'Blue',
        description: 'Comfort sedan currently unavailable due to scheduled service.',
        features: ['Heated seats', 'CarPlay', 'Lane assist'],
        hasGpsSignal: false,
      ),
      Car(
        id: 'car-5',
        brand: 'Nissan',
        model: 'X-Trail',
        year: 2013,
        type: 'Crossover',
        category: 'Family',
        pricePerHour: 16600,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2140, lng: 76.9030),
        imageUrl:
            'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 78,
        rangeKm: 520,
        seats: 5,
        transmission: 'Automatic',
        color: 'Gray',
        description:
            'Imported from the provided dataset: Nissan X-Trail crossover, 2013, petrol, full drive.',
        features: ['Full drive', 'Petrol engine', 'High clearance', 'Family trips'],
      ),
      Car(
        id: 'car-6',
        brand: 'Mercedes-Benz',
        model: 'E-Class',
        year: 2011,
        type: 'Sedan',
        category: 'Business',
        pricePerHour: 20500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2470, lng: 76.8870),
        imageUrl:
            'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 69,
        rangeKm: 610,
        seats: 5,
        transmission: 'Automatic',
        color: 'Black',
        description:
            'Imported from the provided dataset: Mercedes-Benz E-Class sedan, 2011, gas, rear drive.',
        features: ['Business class', 'Rear drive', 'Leather interior', 'Long-route comfort'],
      ),
      Car(
        id: 'car-7',
        brand: 'Ford',
        model: 'Kuga',
        year: 2010,
        type: 'Crossover',
        category: 'Family',
        pricePerHour: 15500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2330, lng: 76.9110),
        imageUrl:
            'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 74,
        rangeKm: 500,
        seats: 5,
        transmission: 'Automatic',
        color: 'Graphite',
        description:
            'Imported from the provided dataset: Ford Kuga crossover, 2010, 2.5 gas, all-wheel drive.',
        features: ['All-wheel drive', 'Raised suspension', 'Family comfort', 'Weekend trips'],
      ),
      Car(
        id: 'car-8',
        brand: 'Renault',
        model: 'Megane',
        year: 2011,
        type: 'Wagon',
        category: 'Comfort',
        pricePerHour: 10500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2560, lng: 76.8740),
        imageUrl:
            'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 66,
        rangeKm: 560,
        seats: 5,
        transmission: 'Manual',
        color: 'White',
        description:
            'Imported from the provided dataset: Renault Megane wagon, 2011, diesel, front drive.',
        features: ['Diesel economy', 'Large trunk', 'Road trip setup', 'Comfort ride'],
        hasGpsSignal: false,
      ),
    ];
  }

  static List<Booking> bookings() {
    return [
      Booking(
        id: 'booking-1',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-2',
        carName: 'Hyundai Sonata',
        startTime: DateTime(2026, 3, 24, 10),
        endTime: DateTime(2026, 3, 24, 18),
        status: BookingStatus.confirmed,
        totalPrice: 56000,
        distanceKm: 0,
        routeSummary: 'Upcoming city rental',
      ),
      Booking(
        id: 'booking-2',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-1',
        carName: 'Tesla Model 3',
        startTime: DateTime(2026, 3, 18, 9),
        endTime: DateTime(2026, 3, 18, 13),
        status: BookingStatus.completed,
        totalPrice: 34000,
        distanceKm: 48.5,
        routeSummary: 'Almaty center to Medeu',
      ),
      Booking(
        id: 'booking-3',
        userId: 'user-2',
        userName: 'Nikita P.',
        carId: 'car-3',
        carName: 'Toyota RAV4',
        startTime: DateTime(2026, 3, 22, 8),
        endTime: DateTime(2026, 3, 22, 20),
        status: BookingStatus.active,
        totalPrice: 110400,
        distanceKm: 132.4,
        routeSummary: 'Airport transfer and regional trip',
      ),
      Booking(
        id: 'booking-4',
        userId: 'admin-1',
        userName: 'Fleet Admin',
        carId: 'car-6',
        carName: 'Mercedes-Benz E-Class',
        startTime: DateTime(2026, 3, 25, 9),
        endTime: DateTime(2026, 3, 27, 18),
        status: BookingStatus.confirmed,
        totalPrice: 123000,
        distanceKm: 0,
        routeSummary: 'Executive multi-day rental',
      ),
      Booking(
        id: 'booking-5',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-5',
        carName: 'Nissan X-Trail',
        startTime: DateTime(2026, 3, 26, 8),
        endTime: DateTime(2026, 3, 28, 20),
        status: BookingStatus.created,
        totalPrice: 199200,
        distanceKm: 0,
        routeSummary: 'Upcoming weekend route',
      ),
    ];
  }

  static List<AppNotification> notifications() {
    return [
      AppNotification(
        id: 'notification-1',
        title: 'Booking confirmed',
        message: 'Hyundai Sonata is confirmed for 24 March, 10:00 to 18:00.',
        type: AppNotificationType.booking,
        createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
      ),
      AppNotification(
        id: 'notification-2',
        title: 'Geofence warning',
        message: 'Toyota RAV4 touched the south geofence boundary.',
        type: AppNotificationType.geofence,
        createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      AppNotification(
        id: 'notification-3',
        title: 'Rental reminder',
        message: 'The active rental ends in 30 minutes.',
        type: AppNotificationType.reminder,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      AppNotification(
        id: 'notification-4',
        title: 'System sync',
        message: 'Last GPS batch was persisted successfully.',
        type: AppNotificationType.system,
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      ),
    ];
  }
}
