import '../models/app_notification.dart';
import '../models/app_role.dart';
import '../models/app_user.dart';
import '../models/booking.dart';
import '../models/car.dart';
import '../models/geo_point.dart';

class DemoSeedData {
  const DemoSeedData._();

  static List<AppUser> users() {
    return [
      AppUser(
        id: 'user-1',
        name: 'Aruzhan S.',
        email: 'user@demo.app',
        phone: '+7 700 000 0001',
        role: AppRole.user,
        licenseNumber: 'KZ-USER-001',
        photoUrl:
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 1, 15),
      ),
      AppUser(
        id: 'admin-1',
        name: 'Fleet Admin',
        email: 'admin@demo.app',
        phone: '+7 700 000 0002',
        role: AppRole.admin,
        licenseNumber: 'KZ-ADMIN-001',
        photoUrl:
            'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 1, 10),
      ),
      AppUser(
        id: 'user-2',
        name: 'Nikita P.',
        email: 'nikita@demo.app',
        phone: '+7 700 000 0003',
        role: AppRole.user,
        licenseNumber: 'KZ-USER-002',
        photoUrl:
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
        createdAt: DateTime(2026, 2, 3),
        isBlocked: true,
      ),
    ];
  }

  static List<Car> cars() {
    return [
      Car(
        id: 'car-1',
        brand: 'Tesla',
        model: 'Model 3',
        year: 2023,
        type: 'Sedan',
        category: 'Electric',
        pricePerHour: 8500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2389, lng: 76.8897),
        imageUrl: '',
        batteryLevel: 86,
        rangeKm: 410,
        seats: 5,
        transmission: 'Automatic',
        color: 'Pearl White',
        description: 'Premium electric sedan for city and business rentals.',
        features: [
          'Autopilot',
          'Panoramic roof',
          'Fast charging',
          'Premium audio'
        ],
        fuelType: 'Electric',
      ),
      Car(
        id: 'car-2',
        brand: 'Hyundai',
        model: 'Sonata',
        year: 2022,
        type: 'Business',
        category: 'Business',
        pricePerHour: 7000,
        status: CarStatus.booked,
        location: GeoPoint(lat: 43.2510, lng: 76.9280),
        imageUrl: '',
        batteryLevel: 64,
        rangeKm: 540,
        seats: 5,
        transmission: 'Automatic',
        color: 'Black',
        description: 'Comfortable business-class sedan for long urban trips.',
        features: ['Climate control', 'Leather seats', 'Rear camera'],
      ),
      Car(
        id: 'car-3',
        brand: 'Toyota',
        model: 'RAV4',
        year: 2024,
        type: 'SUV',
        category: 'Family',
        pricePerHour: 9200,
        status: CarStatus.inUse,
        location: GeoPoint(lat: 43.2220, lng: 76.8510),
        imageUrl: '',
        batteryLevel: 73,
        rangeKm: 480,
        seats: 5,
        transmission: 'Automatic',
        color: 'Silver',
        description: 'Reliable SUV for family travel and regional routes.',
        features: ['AWD', 'Spacious trunk', 'Adaptive cruise'],
      ),
      Car(
        id: 'car-4',
        brand: 'Kia',
        model: 'K5',
        year: 2021,
        type: 'Comfort',
        category: 'Comfort',
        pricePerHour: 6200,
        status: CarStatus.maintenance,
        location: GeoPoint(lat: 43.2650, lng: 76.9450),
        imageUrl: '',
        batteryLevel: 51,
        rangeKm: 450,
        seats: 5,
        transmission: 'Automatic',
        color: 'Blue',
        description:
            'Comfort sedan currently unavailable due to scheduled service.',
        features: ['Heated seats', 'CarPlay', 'Lane assist'],
        hasGpsSignal: false,
      ),
      Car(
        id: 'car-5',
        brand: 'Nissan',
        model: 'X-Trail',
        year: 2013,
        type: 'Crossover',
        category: 'Family',
        pricePerHour: 16600,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2140, lng: 76.9030),
        imageUrl:
            'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 78,
        rangeKm: 520,
        seats: 5,
        transmission: 'Automatic',
        color: 'Gray',
        description:
            'Imported from the provided dataset: Nissan X-Trail crossover, 2013, petrol, full drive.',
        features: [
          'Full drive',
          'Petrol engine',
          'High clearance',
          'Family trips'
        ],
      ),
      Car(
        id: 'car-6',
        brand: 'Mercedes-Benz',
        model: 'E-Class',
        year: 2011,
        type: 'Sedan',
        category: 'Business',
        pricePerHour: 20500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2470, lng: 76.8870),
        imageUrl:
            'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 69,
        rangeKm: 610,
        seats: 5,
        transmission: 'Automatic',
        color: 'Black',
        description:
            'Imported from the provided dataset: Mercedes-Benz E-Class sedan, 2011, gas, rear drive.',
        features: [
          'Business class',
          'Rear drive',
          'Leather interior',
          'Long-route comfort'
        ],
      ),
      Car(
        id: 'car-7',
        brand: 'Ford',
        model: 'Kuga',
        year: 2010,
        type: 'Crossover',
        category: 'Family',
        pricePerHour: 15500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2330, lng: 76.9110),
        imageUrl:
            'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 74,
        rangeKm: 500,
        seats: 5,
        transmission: 'Automatic',
        color: 'Graphite',
        description:
            'Imported from the provided dataset: Ford Kuga crossover, 2010, 2.5 gas, all-wheel drive.',
        features: [
          'All-wheel drive',
          'Raised suspension',
          'Family comfort',
          'Weekend trips'
        ],
      ),
      Car(
        id: 'car-8',
        brand: 'Renault',
        model: 'Megane',
        year: 2011,
        type: 'Wagon',
        category: 'Comfort',
        pricePerHour: 10500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2560, lng: 76.8740),
        imageUrl:
            'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 66,
        rangeKm: 560,
        seats: 5,
        transmission: 'Manual',
        color: 'White',
        description:
            'Imported from the provided dataset: Renault Megane wagon, 2011, diesel, front drive.',
        features: [
          'Diesel economy',
          'Large trunk',
          'Road trip setup',
          'Comfort ride'
        ],
        hasGpsSignal: false,
      ),
      Car(
        id: 'car-9',
        brand: 'BMW',
        model: 'X5',
        year: 2022,
        type: 'SUV',
        category: 'Business',
        pricePerHour: 24000,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2365, lng: 76.9453),
        imageUrl:
            'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 82,
        rangeKm: 590,
        seats: 5,
        transmission: 'Automatic',
        color: 'Dark Blue',
        description: 'Executive SUV with premium cabin and active safety.',
        features: ['AWD', 'Premium audio', 'Panoramic roof', 'Adaptive cruise'],
      ),
      Car(
        id: 'car-10',
        brand: 'Audi',
        model: 'A6',
        year: 2021,
        type: 'Sedan',
        category: 'Business',
        pricePerHour: 18500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2451, lng: 76.9004),
        imageUrl:
            'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 76,
        rangeKm: 610,
        seats: 5,
        transmission: 'Automatic',
        color: 'White',
        description:
            'Business sedan for meetings, airport transfers and daily routes.',
        features: [
          'Matrix lights',
          'Leather interior',
          'Quiet cabin',
          'Navigation'
        ],
      ),
      Car(
        id: 'car-11',
        brand: 'Volkswagen',
        model: 'ID.4',
        year: 2024,
        type: 'Crossover',
        category: 'Electric',
        pricePerHour: 12500,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2298, lng: 76.8921),
        imageUrl:
            'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 91,
        rangeKm: 520,
        seats: 5,
        transmission: 'Automatic',
        color: 'Silver',
        description:
            'Electric crossover with practical cargo space and fast charging.',
        features: [
          'Fast charging',
          'Electric drive',
          'Large trunk',
          'Lane assist'
        ],
        fuelType: 'Electric',
      ),
      Car(
        id: 'car-12',
        brand: 'Chevrolet',
        model: 'Camaro',
        year: 2020,
        type: 'Sport',
        category: 'Comfort',
        pricePerHour: 22000,
        status: CarStatus.booked,
        location: GeoPoint(lat: 43.2186, lng: 76.9275),
        imageUrl:
            'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 70,
        rangeKm: 430,
        seats: 4,
        transmission: 'Automatic',
        color: 'Yellow',
        description: 'Sport coupe for short premium trips and special events.',
        features: ['Sport mode', 'Premium audio', 'Rear camera', 'Low mileage'],
      ),
      Car(
        id: 'car-13',
        brand: 'Skoda',
        model: 'Kodiaq',
        year: 2022,
        type: 'SUV',
        category: 'Family',
        pricePerHour: 11800,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2578, lng: 76.8849),
        imageUrl:
            'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 79,
        rangeKm: 650,
        seats: 7,
        transmission: 'Automatic',
        color: 'Gray',
        description:
            'Seven-seat family SUV for city errands and weekend routes.',
        features: ['7 seats', 'Large trunk', 'Child seat anchors', 'AWD'],
      ),
      Car(
        id: 'car-14',
        brand: 'Lexus',
        model: 'RX',
        year: 2023,
        type: 'SUV',
        category: 'Business',
        pricePerHour: 26000,
        status: CarStatus.inUse,
        location: GeoPoint(lat: 43.2413, lng: 76.9348),
        imageUrl:
            'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 83,
        rangeKm: 580,
        seats: 5,
        transmission: 'Automatic',
        color: 'Black',
        description: 'Premium SUV with quiet ride and high comfort level.',
        features: [
          'Hybrid system',
          'Ventilated seats',
          'Premium audio',
          '360 camera'
        ],
      ),
      Car(
        id: 'car-15',
        brand: 'Toyota',
        model: 'Camry',
        year: 2023,
        type: 'Sedan',
        category: 'Comfort',
        pricePerHour: 9800,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2319, lng: 76.8726),
        imageUrl:
            'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 77,
        rangeKm: 620,
        seats: 5,
        transmission: 'Automatic',
        color: 'White',
        description: 'Reliable comfort sedan for everyday rentals.',
        features: [
          'Climate control',
          'Rear camera',
          'Adaptive cruise',
          'USB-C'
        ],
      ),
      Car(
        id: 'car-16',
        brand: 'Hyundai',
        model: 'Staria',
        year: 2023,
        type: 'Van',
        category: 'Family',
        pricePerHour: 14000,
        status: CarStatus.available,
        location: GeoPoint(lat: 43.2681, lng: 76.9122),
        imageUrl:
            'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
        batteryLevel: 72,
        rangeKm: 560,
        seats: 8,
        transmission: 'Automatic',
        color: 'Silver',
        description:
            'Spacious van for family trips, teams and airport transfers.',
        features: [
          '8 seats',
          'Sliding doors',
          'Large luggage area',
          'Rear climate'
        ],
      ),
      ..._datasetCars(),
    ];
  }

  static List<Car> _datasetCars() {
    return [
      _datasetCar('car-17', 'Mercedes-Benz', 'CL 550', 2008, 'Other', 35000,
          135, 5.5, 'Petrol', 'rear', 4),
      _datasetCar('car-18', 'Mercedes-Benz', 'B 180', 2012, 'Van', 17800, 162,
          1.8, 'Diesel', 'front', 5),
      _datasetCar('car-19', 'Mercedes-Benz', 'E-Class', 2010, 'Sedan', 22700,
          125, 2.2, 'Diesel', 'rear', 5),
      _datasetCar('car-20', 'Nissan', 'Qashqai', 2016, 'Crossover', 20447, 0,
          1.2, 'Petrol', 'front', 5),
      _datasetCar('car-21', 'BMW', '316', 1996, 'Sedan', 4700, 200, null,
          'Petrol', 'rear', 5),
      _datasetCar('car-22', 'BMW', '750', 2016, 'Sedan', 129222, 2, 5.0,
          'Petrol', 'full', 5),
      _datasetCar('car-23', 'Mercedes-Benz', 'GLE-Class', 2016, 'Crossover',
          99999, 0, 3.0, 'Petrol', 'full', 5),
      _datasetCar('car-24', 'BMW', 'M5', 2013, 'Sedan', 73900, 57, 4.4,
          'Petrol', 'rear', 5),
      _datasetCar('car-25', 'Land Rover', 'Range Rover', 2016, 'Crossover',
          69000, 0, 4.4, 'Diesel', 'full', 5),
      _datasetCar('car-26', 'Nissan', 'X-Trail', 2016, 'Crossover', 26034, 0,
          1.6, 'Diesel', 'full', 5),
      _datasetCar('car-27', 'BMW', 'X5', 2016, 'Crossover', 104999, 2, 3.0,
          'Diesel', 'full', 5),
      _datasetCar('car-28', 'BMW', 'X5', 2007, 'Crossover', 23900, 235, 3.0,
          'Diesel', 'full', 5),
      _datasetCar('car-29', 'Nissan', 'Leaf', 2013, 'Hatch', 13980, 31, null,
          'Electric', 'front', 5),
      _datasetCar('car-30', 'Nissan', 'Leaf', 2013, 'Hatch', 17300, 24, null,
          'Electric', 'front', 5),
      _datasetCar('car-31', 'Volkswagen', 'Passat B6', 2007, 'Sedan', 10700,
          147, 2.0, 'Petrol', 'front', 5),
      _datasetCar('car-32', 'Audi', 'A6', 1999, 'Vagon', 2600, 273, 2.5,
          'Diesel', 'front', 5,
          registered: false),
      _datasetCar('car-33', 'Chrysler', 'Sebring', 2008, 'Sedan', 13700, 70,
          2.4, 'Petrol', 'front', 5),
      _datasetCar('car-34', 'Honda', 'Accord', 2003, 'Sedan', 6500, 199, 2.0,
          'Petrol', 'front', 5),
      _datasetCar('car-35', 'Mercedes-Benz', 'E-Class', 2013, 'Vagon', 33000,
          91, null, 'Other', 'rear', 5),
      _datasetCar('car-36', 'BMW', 'X5', 2015, 'Crossover', 63000, 0, 2.0,
          'Diesel', 'full', 5),
    ];
  }

  static Car _datasetCar(
    String id,
    String brand,
    String model,
    int year,
    String body,
    double price,
    int mileageThousands,
    double? engineVolume,
    String fuelType,
    String drive,
    int seats, {
    bool registered = true,
  }) {
    final isElectric = fuelType.toLowerCase() == 'electric';
    final serial = int.parse(id.split('-').last);
    return Car(
      id: id,
      brand: brand,
      model: model,
      year: year,
      type: body,
      category: isElectric
          ? 'Electric'
          : (body == 'Crossover' || body == 'Van' || body == 'Vagon'
              ? 'Family'
              : 'Business'),
      pricePerHour: price,
      status: CarStatus.available,
      location: GeoPoint(
        lat: 43.20 + (serial % 10) * 0.007,
        lng: 76.86 + (serial % 9) * 0.009,
      ),
      imageUrl: '',
      batteryLevel: isElectric ? 75 : 0,
      rangeKm: isElectric ? 420 : 520,
      seats: seats,
      transmission: 'Automatic',
      color: isElectric ? 'White' : 'Black',
      description:
          'Imported from car_ad.csv: $brand $model, $body, $fuelType, $drive drive.',
      features: [
        fuelType,
        '${mileageThousands}k km mileage',
        '$drive drive',
        'Dataset import'
      ],
      fuelType: fuelType,
      gasLevel: isElectric ? null : 78,
      engineVolume: engineVolume,
      mileageKm: mileageThousands * 1000,
      drive: drive,
      registered: registered,
    );
  }

  static List<Booking> bookings() {
    return [
      Booking(
        id: 'booking-1',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-2',
        carName: 'Hyundai Sonata',
        startTime: DateTime(2026, 3, 24, 10),
        endTime: DateTime(2026, 3, 24, 18),
        status: BookingStatus.confirmed,
        totalPrice: 56000,
        distanceKm: 0,
        routeSummary: 'Upcoming city rental',
      ),
      Booking(
        id: 'booking-2',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-1',
        carName: 'Tesla Model 3',
        startTime: DateTime(2026, 3, 18, 9),
        endTime: DateTime(2026, 3, 18, 13),
        status: BookingStatus.completed,
        totalPrice: 34000,
        distanceKm: 48.5,
        routeSummary: 'Almaty center to Medeu',
      ),
      Booking(
        id: 'booking-3',
        userId: 'user-2',
        userName: 'Nikita P.',
        carId: 'car-3',
        carName: 'Toyota RAV4',
        startTime: DateTime(2026, 3, 22, 8),
        endTime: DateTime(2026, 3, 22, 20),
        status: BookingStatus.active,
        totalPrice: 110400,
        distanceKm: 132.4,
        routeSummary: 'Airport transfer and regional trip',
      ),
      Booking(
        id: 'booking-4',
        userId: 'admin-1',
        userName: 'Fleet Admin',
        carId: 'car-6',
        carName: 'Mercedes-Benz E-Class',
        startTime: DateTime(2026, 3, 25, 9),
        endTime: DateTime(2026, 3, 27, 18),
        status: BookingStatus.confirmed,
        totalPrice: 123000,
        distanceKm: 0,
        routeSummary: 'Executive multi-day rental',
      ),
      Booking(
        id: 'booking-5',
        userId: 'user-1',
        userName: 'Aruzhan S.',
        carId: 'car-5',
        carName: 'Nissan X-Trail',
        startTime: DateTime(2026, 3, 26, 8),
        endTime: DateTime(2026, 3, 28, 20),
        status: BookingStatus.created,
        totalPrice: 199200,
        distanceKm: 0,
        routeSummary: 'Upcoming weekend route',
      ),
    ];
  }

  static List<AppNotification> notifications() {
    return [
      AppNotification(
        id: 'notification-1',
        title: 'Booking confirmed',
        message: 'Hyundai Sonata is confirmed for 24 March, 10:00 to 18:00.',
        type: AppNotificationType.booking,
        createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
      ),
      AppNotification(
        id: 'notification-2',
        title: 'Geofence warning',
        message: 'Toyota RAV4 touched the south geofence boundary.',
        type: AppNotificationType.geofence,
        createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      AppNotification(
        id: 'notification-3',
        title: 'Rental reminder',
        message: 'The active rental ends in 30 minutes.',
        type: AppNotificationType.reminder,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      AppNotification(
        id: 'notification-4',
        title: 'System sync',
        message: 'Last GPS batch was persisted successfully.',
        type: AppNotificationType.system,
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      ),
    ];
  }
}
