from __future__ import annotations

from datetime import datetime, timedelta, timezone


def demo_users() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "user-1",
            "name": "Aruzhan S.",
            "email": "user@demo.app",
            "phone": "+7 700 000 0001",
            "role": "user",
            "license_number": "KZ-USER-001",
            "photo_url": None,
            "password": "demo123",
            "blocked": False,
            "created_at": now,
        },
        {
            "_id": "admin-1",
            "name": "Fleet Admin",
            "email": "admin@demo.app",
            "phone": "+7 700 000 0002",
            "role": "admin",
            "license_number": "KZ-ADMIN-001",
            "photo_url": None,
            "password": "demo123",
            "blocked": False,
            "created_at": now,
        },
        {
            "_id": "user-2",
            "name": "Nikita P.",
            "email": "nikita@demo.app",
            "phone": "+7 700 000 0003",
            "role": "user",
            "license_number": "KZ-USER-002",
            "photo_url": None,
            "password": "demo123",
            "blocked": True,
            "created_at": now,
        },
    ]


def demo_cars() -> list[dict]:
    return [
        {
            "_id": "car-1",
            "brand": "Tesla",
            "model": "Model 3",
            "year": 2023,
            "type": "Sedan",
            "category": "Electric",
            "price_per_hour": 8500,
            "status": "available",
            "battery_level": 86,
            "range_km": 410,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Pearl White",
            "description": "Premium electric sedan for city and business rentals.",
            "features": ["Autopilot", "Panoramic roof", "Fast charging"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2389, "lng": 76.8897},
        },
        {
            "_id": "car-2",
            "brand": "Hyundai",
            "model": "Sonata",
            "year": 2022,
            "type": "Business",
            "category": "Business",
            "price_per_hour": 7000,
            "status": "booked",
            "battery_level": 64,
            "range_km": 540,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Black",
            "description": "Comfortable business sedan.",
            "features": ["Rear camera", "Leather seats"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2510, "lng": 76.9280},
        },
        {
            "_id": "car-3",
            "brand": "Toyota",
            "model": "RAV4",
            "year": 2024,
            "type": "SUV",
            "category": "Family",
            "price_per_hour": 9200,
            "status": "inUse",
            "battery_level": 73,
            "range_km": 480,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Silver",
            "description": "Reliable SUV for family travel.",
            "features": ["AWD", "Adaptive cruise"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2220, "lng": 76.8510},
        },
        {
            "_id": "car-4",
            "brand": "Kia",
            "model": "K5",
            "year": 2021,
            "type": "Comfort",
            "category": "Comfort",
            "price_per_hour": 6200,
            "status": "maintenance",
            "battery_level": 51,
            "range_km": 450,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Blue",
            "description": "Comfort sedan currently unavailable due to scheduled service.",
            "features": ["Heated seats", "CarPlay", "Lane assist"],
            "image_url": "",
            "has_gps_signal": False,
            "location": {"lat": 43.2650, "lng": 76.9450},
        },
        {
            "_id": "car-5",
            "brand": "Nissan",
            "model": "X-Trail",
            "year": 2013,
            "type": "Crossover",
            "category": "Family",
            "price_per_hour": 16600,
            "status": "available",
            "battery_level": 78,
            "range_km": 520,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Gray",
            "description": "Imported from the provided dataset: Nissan X-Trail crossover, 2013, petrol, full drive.",
            "features": ["Full drive", "Petrol engine", "High clearance", "Family trips"],
            "image_url": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2140, "lng": 76.9030},
        },
        {
            "_id": "car-6",
            "brand": "Mercedes-Benz",
            "model": "E-Class",
            "year": 2011,
            "type": "Sedan",
            "category": "Business",
            "price_per_hour": 20500,
            "status": "available",
            "battery_level": 69,
            "range_km": 610,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Black",
            "description": "Imported from the provided dataset: Mercedes-Benz E-Class sedan, 2011, gas, rear drive.",
            "features": ["Business class", "Rear drive", "Leather interior", "Long-route comfort"],
            "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2470, "lng": 76.8870},
        },
        {
            "_id": "car-7",
            "brand": "Ford",
            "model": "Kuga",
            "year": 2010,
            "type": "Crossover",
            "category": "Family",
            "price_per_hour": 15500,
            "status": "available",
            "battery_level": 74,
            "range_km": 500,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Graphite",
            "description": "Imported from the provided dataset: Ford Kuga crossover, 2010, 2.5 gas, all-wheel drive.",
            "features": ["All-wheel drive", "Raised suspension", "Family comfort", "Weekend trips"],
            "image_url": "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2330, "lng": 76.9110},
        },
        {
            "_id": "car-8",
            "brand": "Renault",
            "model": "Megane",
            "year": 2011,
            "type": "Wagon",
            "category": "Comfort",
            "price_per_hour": 10500,
            "status": "available",
            "battery_level": 66,
            "range_km": 560,
            "seats": 5,
            "transmission": "Manual",
            "color": "White",
            "description": "Imported from the provided dataset: Renault Megane wagon, 2011, diesel, front drive.",
            "features": ["Diesel economy", "Large trunk", "Road trip setup", "Comfort ride"],
            "image_url": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": False,
            "location": {"lat": 43.2560, "lng": 76.8740},
        },
    ]


def demo_bookings() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "booking-1",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-2",
            "car_name": "Hyundai Sonata",
            "start_time": now + timedelta(days=1, hours=2),
            "end_time": now + timedelta(days=1, hours=10),
            "status": "confirmed",
            "total_price": 56000,
            "distance_km": 0,
            "route_summary": "Upcoming city rental",
        },
        {
            "_id": "booking-2",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-1",
            "car_name": "Tesla Model 3",
            "start_time": now - timedelta(days=3, hours=4),
            "end_time": now - timedelta(days=3),
            "status": "completed",
            "total_price": 34000,
            "distance_km": 48.5,
            "route_summary": "Almaty center to Medeu",
        },
        {
            "_id": "booking-3",
            "user_id": "user-2",
            "user_name": "Nikita P.",
            "car_id": "car-3",
            "car_name": "Toyota RAV4",
            "start_time": now - timedelta(days=2, hours=4),
            "end_time": now - timedelta(days=1, hours=16),
            "status": "active",
            "total_price": 110400,
            "distance_km": 132.4,
            "route_summary": "Airport transfer and regional trip",
        },
        {
            "_id": "booking-4",
            "user_id": "admin-1",
            "user_name": "Fleet Admin",
            "car_id": "car-6",
            "car_name": "Mercedes-Benz E-Class",
            "start_time": now + timedelta(days=1, hours=1),
            "end_time": now + timedelta(days=3, hours=10),
            "status": "confirmed",
            "total_price": 123000,
            "distance_km": 0,
            "route_summary": "Executive multi-day rental",
        },
        {
            "_id": "booking-5",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-5",
            "car_name": "Nissan X-Trail",
            "start_time": now + timedelta(days=2, hours=8),
            "end_time": now + timedelta(days=4, hours=20),
            "status": "created",
            "total_price": 199200,
            "distance_km": 0,
            "route_summary": "Upcoming weekend route",
        },
    ]


def demo_notifications() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "notification-1",
            "title": "Booking confirmed",
            "message": "Hyundai Sonata is confirmed for tomorrow.",
            "type": "booking",
            "created_at": now - timedelta(minutes=15),
        },
        {
            "_id": "notification-2",
            "title": "Geofence warning",
            "message": "Toyota RAV4 touched the south geofence boundary.",
            "type": "geofence",
            "created_at": now - timedelta(hours=1),
        },
    ]


def demo_tracking() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "car-1",
            "car_id": "car-1",
            "lat": 43.2389,
            "lng": 76.8897,
            "speed_kph": 42,
            "is_inside_geofence": True,
            "geofence_name": "Almaty south sector",
            "distance_km": 31.4,
            "updated_at": now.isoformat(),
            "route": [
                {"lat": 43.2389, "lng": 76.8897},
                {"lat": 43.2421, "lng": 76.9012},
            ],
        },
        {
            "_id": "car-2",
            "car_id": "car-2",
            "lat": 43.2510,
            "lng": 76.9280,
            "speed_kph": 0,
            "is_inside_geofence": True,
            "geofence_name": "Almaty south sector",
            "distance_km": 0,
            "updated_at": now.isoformat(),
            "route": [],
        },
        {
            "_id": "car-6",
            "car_id": "car-6",
            "lat": 43.2470,
            "lng": 76.8870,
            "speed_kph": 0,
            "is_inside_geofence": True,
            "geofence_name": "Almaty business sector",
            "distance_km": 0,
            "updated_at": now.isoformat(),
            "route": [],
        },
    ]
