from __future__ import annotations

from datetime import datetime, timedelta, timezone


def demo_users() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "user-1",
            "name": "Aruzhan S.",
            "email": "user@demo.app",
            "phone": "+7 700 000 0001",
            "role": "user",
            "license_number": "KZ-USER-001",
            "photo_url": None,
            "password": "demo123",
            "blocked": False,
            "created_at": now,
        },
        {
            "_id": "admin-1",
            "name": "Fleet Admin",
            "email": "admin@demo.app",
            "phone": "+7 700 000 0002",
            "role": "admin",
            "license_number": "KZ-ADMIN-001",
            "photo_url": None,
            "password": "demo123",
            "blocked": False,
            "created_at": now,
        },
        {
            "_id": "user-2",
            "name": "Nikita P.",
            "email": "nikita@demo.app",
            "phone": "+7 700 000 0003",
            "role": "user",
            "license_number": "KZ-USER-002",
            "photo_url": None,
            "password": "demo123",
            "blocked": True,
            "created_at": now,
        },
    ]


def demo_cars() -> list[dict]:
    cars = [
        {
            "_id": "car-1",
            "brand": "Tesla",
            "model": "Model 3",
            "year": 2023,
            "type": "Sedan",
            "category": "Electric",
            "price_per_hour": 8500,
            "status": "available",
            "battery_level": 86,
            "range_km": 410,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Pearl White",
            "description": "Premium electric sedan for city and business rentals.",
            "features": ["Autopilot", "Panoramic roof", "Fast charging"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2389, "lng": 76.8897},
        },
        {
            "_id": "car-2",
            "brand": "Hyundai",
            "model": "Sonata",
            "year": 2022,
            "type": "Business",
            "category": "Business",
            "price_per_hour": 7000,
            "status": "booked",
            "battery_level": 64,
            "range_km": 540,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Black",
            "description": "Comfortable business sedan.",
            "features": ["Rear camera", "Leather seats"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2510, "lng": 76.9280},
        },
        {
            "_id": "car-3",
            "brand": "Toyota",
            "model": "RAV4",
            "year": 2024,
            "type": "SUV",
            "category": "Family",
            "price_per_hour": 9200,
            "status": "inUse",
            "battery_level": 73,
            "range_km": 480,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Silver",
            "description": "Reliable SUV for family travel.",
            "features": ["AWD", "Adaptive cruise"],
            "image_url": "",
            "has_gps_signal": True,
            "location": {"lat": 43.2220, "lng": 76.8510},
        },
        {
            "_id": "car-4",
            "brand": "Kia",
            "model": "K5",
            "year": 2021,
            "type": "Comfort",
            "category": "Comfort",
            "price_per_hour": 6200,
            "status": "maintenance",
            "battery_level": 51,
            "range_km": 450,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Blue",
            "description": "Comfort sedan currently unavailable due to scheduled service.",
            "features": ["Heated seats", "CarPlay", "Lane assist"],
            "image_url": "",
            "has_gps_signal": False,
            "location": {"lat": 43.2650, "lng": 76.9450},
        },
        {
            "_id": "car-5",
            "brand": "Nissan",
            "model": "X-Trail",
            "year": 2013,
            "type": "Crossover",
            "category": "Family",
            "price_per_hour": 16600,
            "status": "available",
            "battery_level": 78,
            "range_km": 520,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Gray",
            "description": "Imported from the provided dataset: Nissan X-Trail crossover, 2013, petrol, full drive.",
            "features": ["Full drive", "Petrol engine", "High clearance", "Family trips"],
            "image_url": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2140, "lng": 76.9030},
        },
        {
            "_id": "car-6",
            "brand": "Mercedes-Benz",
            "model": "E-Class",
            "year": 2011,
            "type": "Sedan",
            "category": "Business",
            "price_per_hour": 20500,
            "status": "available",
            "battery_level": 69,
            "range_km": 610,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Black",
            "description": "Imported from the provided dataset: Mercedes-Benz E-Class sedan, 2011, gas, rear drive.",
            "features": ["Business class", "Rear drive", "Leather interior", "Long-route comfort"],
            "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2470, "lng": 76.8870},
        },
        {
            "_id": "car-7",
            "brand": "Ford",
            "model": "Kuga",
            "year": 2010,
            "type": "Crossover",
            "category": "Family",
            "price_per_hour": 15500,
            "status": "available",
            "battery_level": 74,
            "range_km": 500,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Graphite",
            "description": "Imported from the provided dataset: Ford Kuga crossover, 2010, 2.5 gas, all-wheel drive.",
            "features": ["All-wheel drive", "Raised suspension", "Family comfort", "Weekend trips"],
            "image_url": "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2330, "lng": 76.9110},
        },
        {
            "_id": "car-8",
            "brand": "Renault",
            "model": "Megane",
            "year": 2011,
            "type": "Wagon",
            "category": "Comfort",
            "price_per_hour": 10500,
            "status": "available",
            "battery_level": 66,
            "range_km": 560,
            "seats": 5,
            "transmission": "Manual",
            "color": "White",
            "description": "Imported from the provided dataset: Renault Megane wagon, 2011, diesel, front drive.",
            "features": ["Diesel economy", "Large trunk", "Road trip setup", "Comfort ride"],
            "image_url": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": False,
            "location": {"lat": 43.2560, "lng": 76.8740},
        },
        {
            "_id": "car-9",
            "brand": "BMW",
            "model": "X5",
            "year": 2022,
            "type": "SUV",
            "category": "Business",
            "price_per_hour": 24000,
            "status": "available",
            "battery_level": 82,
            "range_km": 590,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Dark Blue",
            "description": "Executive SUV with premium cabin and active safety.",
            "features": ["AWD", "Premium audio", "Panoramic roof", "Adaptive cruise"],
            "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2365, "lng": 76.9453},
        },
        {
            "_id": "car-10",
            "brand": "Audi",
            "model": "A6",
            "year": 2021,
            "type": "Sedan",
            "category": "Business",
            "price_per_hour": 18500,
            "status": "available",
            "battery_level": 76,
            "range_km": 610,
            "seats": 5,
            "transmission": "Automatic",
            "color": "White",
            "description": "Business sedan for meetings, airport transfers and daily routes.",
            "features": ["Matrix lights", "Leather interior", "Quiet cabin", "Navigation"],
            "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2451, "lng": 76.9004},
        },
        {
            "_id": "car-11",
            "brand": "Volkswagen",
            "model": "ID.4",
            "year": 2024,
            "type": "Crossover",
            "category": "Electric",
            "price_per_hour": 12500,
            "status": "available",
            "battery_level": 91,
            "range_km": 520,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Silver",
            "description": "Electric crossover with practical cargo space and fast charging.",
            "features": ["Fast charging", "Electric drive", "Large trunk", "Lane assist"],
            "image_url": "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2298, "lng": 76.8921},
        },
        {
            "_id": "car-12",
            "brand": "Chevrolet",
            "model": "Camaro",
            "year": 2020,
            "type": "Sport",
            "category": "Comfort",
            "price_per_hour": 22000,
            "status": "booked",
            "battery_level": 70,
            "range_km": 430,
            "seats": 4,
            "transmission": "Automatic",
            "color": "Yellow",
            "description": "Sport coupe for short premium trips and special events.",
            "features": ["Sport mode", "Premium audio", "Rear camera", "Low mileage"],
            "image_url": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2186, "lng": 76.9275},
        },
        {
            "_id": "car-13",
            "brand": "Skoda",
            "model": "Kodiaq",
            "year": 2022,
            "type": "SUV",
            "category": "Family",
            "price_per_hour": 11800,
            "status": "available",
            "battery_level": 79,
            "range_km": 650,
            "seats": 7,
            "transmission": "Automatic",
            "color": "Gray",
            "description": "Seven-seat family SUV for city errands and weekend routes.",
            "features": ["7 seats", "Large trunk", "Child seat anchors", "AWD"],
            "image_url": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2578, "lng": 76.8849},
        },
        {
            "_id": "car-14",
            "brand": "Lexus",
            "model": "RX",
            "year": 2023,
            "type": "SUV",
            "category": "Business",
            "price_per_hour": 26000,
            "status": "inUse",
            "battery_level": 83,
            "range_km": 580,
            "seats": 5,
            "transmission": "Automatic",
            "color": "Black",
            "description": "Premium SUV with quiet ride and high comfort level.",
            "features": ["Hybrid system", "Ventilated seats", "Premium audio", "360 camera"],
            "image_url": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2413, "lng": 76.9348},
        },
        {
            "_id": "car-15",
            "brand": "Toyota",
            "model": "Camry",
            "year": 2023,
            "type": "Sedan",
            "category": "Comfort",
            "price_per_hour": 9800,
            "status": "available",
            "battery_level": 77,
            "range_km": 620,
            "seats": 5,
            "transmission": "Automatic",
            "color": "White",
            "description": "Reliable comfort sedan for everyday rentals.",
            "features": ["Climate control", "Rear camera", "Adaptive cruise", "USB-C"],
            "image_url": "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2319, "lng": 76.8726},
        },
        {
            "_id": "car-16",
            "brand": "Hyundai",
            "model": "Staria",
            "year": 2023,
            "type": "Van",
            "category": "Family",
            "price_per_hour": 14000,
            "status": "available",
            "battery_level": 72,
            "range_km": 560,
            "seats": 8,
            "transmission": "Automatic",
            "color": "Silver",
            "description": "Spacious van for family trips, teams and airport transfers.",
            "features": ["8 seats", "Sliding doors", "Large luggage area", "Rear climate"],
            "image_url": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
            "has_gps_signal": True,
            "location": {"lat": 43.2681, "lng": 76.9122},
        },
    ]
    cars.extend([
        _dataset_car("car-17", "Mercedes-Benz", "CL 550", 2008, "other", 35000, 135, 5.5, "Petrol", "rear", 4),
        _dataset_car("car-18", "Mercedes-Benz", "B 180", 2012, "van", 17800, 162, 1.8, "Diesel", "front", 5),
        _dataset_car("car-19", "Mercedes-Benz", "E-Class", 2010, "sedan", 22700, 125, 2.2, "Diesel", "rear", 5),
        _dataset_car("car-20", "Nissan", "Qashqai", 2016, "crossover", 20447, 0, 1.2, "Petrol", "front", 5),
        _dataset_car("car-21", "BMW", "316", 1996, "sedan", 4700, 200, None, "Petrol", "rear", 5),
        _dataset_car("car-22", "BMW", "750", 2016, "sedan", 129222, 2, 5.0, "Petrol", "full", 5),
        _dataset_car("car-23", "Mercedes-Benz", "GLE-Class", 2016, "crossover", 99999, 0, 3.0, "Petrol", "full", 5),
        _dataset_car("car-24", "BMW", "M5", 2013, "sedan", 73900, 57, 4.4, "Petrol", "rear", 5),
        _dataset_car("car-25", "Land Rover", "Range Rover", 2016, "crossover", 69000, 0, 4.4, "Diesel", "full", 5),
        _dataset_car("car-26", "Nissan", "X-Trail", 2016, "crossover", 26034, 0, 1.6, "Diesel", "full", 5),
        _dataset_car("car-27", "BMW", "X5", 2016, "crossover", 104999, 2, 3.0, "Diesel", "full", 5),
        _dataset_car("car-28", "BMW", "X5", 2007, "crossover", 23900, 235, 3.0, "Diesel", "full", 5),
        _dataset_car("car-29", "Nissan", "Leaf", 2013, "hatch", 13980, 31, None, "Electric", "front", 5),
        _dataset_car("car-30", "Nissan", "Leaf", 2013, "hatch", 17300, 24, None, "Electric", "front", 5),
        _dataset_car("car-31", "Volkswagen", "Passat B6", 2007, "sedan", 10700, 147, 2.0, "Petrol", "front", 5),
        _dataset_car("car-32", "Audi", "A6", 1999, "vagon", 2600, 273, 2.5, "Diesel", "front", 5, registered=False),
        _dataset_car("car-33", "Chrysler", "Sebring", 2008, "sedan", 13700, 70, 2.4, "Petrol", "front", 5),
        _dataset_car("car-34", "Honda", "Accord", 2003, "sedan", 6500, 199, 2.0, "Petrol", "front", 5),
        _dataset_car("car-35", "Mercedes-Benz", "E-Class", 2013, "vagon", 33000, 91, None, "Other", "rear", 5),
        _dataset_car("car-36", "BMW", "X5", 2015, "crossover", 63000, 0, 2.0, "Diesel", "full", 5),
    ])
    return [_with_car_defaults(item) for item in cars]


def _dataset_car(
    car_id: str,
    brand: str,
    model: str,
    year: int,
    body: str,
    price: float,
    mileage: int,
    engine_volume: float | None,
    fuel_type: str,
    drive: str,
    seats: int,
    *,
    registered: bool = True,
) -> dict:
    is_electric = fuel_type.lower() == "electric"
    category = "Electric" if is_electric else ("Family" if body in {"crossover", "van", "vagon"} else "Business")
    return {
        "_id": car_id,
        "brand": brand,
        "model": model,
        "year": year,
        "type": body.title(),
        "category": category,
        "price_per_hour": price,
        "status": "available",
        "battery_level": 75 if is_electric else 0,
        "range_km": 420 if is_electric else 520,
        "seats": seats,
        "transmission": "Automatic",
        "color": "White" if is_electric else "Black",
        "description": f"Imported from car_ad.csv: {brand} {model}, {body}, {fuel_type}, {drive} drive.",
        "features": [fuel_type, f"{mileage}k km mileage", f"{drive} drive", "Dataset import"],
        "fuel_type": fuel_type,
        "gas_level": None if is_electric else 78,
        "engine_volume": engine_volume,
        "mileage_km": mileage * 1000,
        "drive": drive,
        "registered": registered,
        "image_url": "",
        "has_gps_signal": True,
        "location": {"lat": 43.20 + (int(car_id.split("-")[1]) % 10) * 0.007, "lng": 76.86 + (int(car_id.split("-")[1]) % 9) * 0.009},
    }


def _with_car_defaults(item: dict) -> dict:
    fuel_type = item.get("fuel_type") or (
        "Electric" if item["brand"].lower() in {"tesla"} or item["model"].lower() in {"leaf", "id.4"} else "Petrol"
    )
    is_electric = fuel_type.lower() == "electric"
    return {
        **item,
        "fuel_type": fuel_type,
        "gas_level": None if is_electric else item.get("gas_level", 70 + (hash(item["_id"]) % 25)),
        "engine_volume": item.get("engine_volume"),
        "mileage_km": item.get("mileage_km", 0),
        "drive": item.get("drive", "front"),
        "registered": item.get("registered", True),
    }


def demo_bookings() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "booking-1",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-2",
            "car_name": "Hyundai Sonata",
            "start_time": now + timedelta(days=1, hours=2),
            "end_time": now + timedelta(days=1, hours=10),
            "status": "confirmed",
            "total_price": 56000,
            "distance_km": 0,
            "route_summary": "Upcoming city rental",
        },
        {
            "_id": "booking-2",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-1",
            "car_name": "Tesla Model 3",
            "start_time": now - timedelta(days=3, hours=4),
            "end_time": now - timedelta(days=3),
            "status": "completed",
            "total_price": 34000,
            "distance_km": 48.5,
            "route_summary": "Almaty center to Medeu",
        },
        {
            "_id": "booking-3",
            "user_id": "user-2",
            "user_name": "Nikita P.",
            "car_id": "car-3",
            "car_name": "Toyota RAV4",
            "start_time": now - timedelta(days=2, hours=4),
            "end_time": now - timedelta(days=1, hours=16),
            "status": "active",
            "total_price": 110400,
            "distance_km": 132.4,
            "route_summary": "Airport transfer and regional trip",
        },
        {
            "_id": "booking-4",
            "user_id": "admin-1",
            "user_name": "Fleet Admin",
            "car_id": "car-6",
            "car_name": "Mercedes-Benz E-Class",
            "start_time": now + timedelta(days=1, hours=1),
            "end_time": now + timedelta(days=3, hours=10),
            "status": "confirmed",
            "total_price": 123000,
            "distance_km": 0,
            "route_summary": "Executive multi-day rental",
        },
        {
            "_id": "booking-5",
            "user_id": "user-1",
            "user_name": "Aruzhan S.",
            "car_id": "car-5",
            "car_name": "Nissan X-Trail",
            "start_time": now + timedelta(days=2, hours=8),
            "end_time": now + timedelta(days=4, hours=20),
            "status": "created",
            "total_price": 199200,
            "distance_km": 0,
            "route_summary": "Upcoming weekend route",
        },
    ]


def demo_notifications() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "notification-1",
            "title": "Booking confirmed",
            "message": "Hyundai Sonata is confirmed for tomorrow.",
            "type": "booking",
            "created_at": now - timedelta(minutes=15),
        },
        {
            "_id": "notification-2",
            "title": "Geofence warning",
            "message": "Toyota RAV4 touched the south geofence boundary.",
            "type": "geofence",
            "created_at": now - timedelta(hours=1),
        },
    ]


def demo_tracking() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "car-1",
            "car_id": "car-1",
            "lat": 43.2389,
            "lng": 76.8897,
            "speed_kph": 42,
            "is_inside_geofence": True,
            "geofence_name": "Almaty south sector",
            "distance_km": 31.4,
            "updated_at": now.isoformat(),
            "route": [
                {"lat": 43.2389, "lng": 76.8897},
                {"lat": 43.2421, "lng": 76.9012},
            ],
        },
        {
            "_id": "car-2",
            "car_id": "car-2",
            "lat": 43.2510,
            "lng": 76.9280,
            "speed_kph": 0,
            "is_inside_geofence": True,
            "geofence_name": "Almaty south sector",
            "distance_km": 0,
            "updated_at": now.isoformat(),
            "route": [],
        },
        {
            "_id": "car-6",
            "car_id": "car-6",
            "lat": 43.2470,
            "lng": 76.8870,
            "speed_kph": 0,
            "is_inside_geofence": True,
            "geofence_name": "Almaty business sector",
            "distance_km": 0,
            "updated_at": now.isoformat(),
            "route": [],
        },
    ]


def demo_wallets() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "wallet-user-1",
            "user_id": "user-1",
            "balance": 120000,
            "currency": "KZT",
            "updated_at": now,
        },
        {
            "_id": "wallet-admin-1",
            "user_id": "admin-1",
            "balance": 500000,
            "currency": "KZT",
            "updated_at": now,
        },
    ]


def demo_transactions() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "transaction-1",
            "user_id": "user-1",
            "booking_id": "booking-1",
            "type": "wallet_top_up",
            "amount": 50000,
            "status": "paid",
            "payment_method": "Visa **** 4242",
            "created_at": now - timedelta(hours=3),
        },
        {
            "_id": "transaction-2",
            "user_id": "user-1",
            "booking_id": "booking-2",
            "type": "booking_payment",
            "amount": -34000,
            "status": "paid",
            "payment_method": "Wallet",
            "created_at": now - timedelta(days=3),
        },
    ]


def demo_favorites() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {"_id": "favorite-user-1-car-1", "user_id": "user-1", "car_id": "car-1", "created_at": now},
        {"_id": "favorite-user-1-car-3", "user_id": "user-1", "car_id": "car-3", "created_at": now},
    ]


def demo_bookmarks() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {"_id": "bookmark-user-1-car-5", "user_id": "user-1", "car_id": "car-5", "created_at": now},
        {"_id": "bookmark-user-1-car-6", "user_id": "user-1", "car_id": "car-6", "created_at": now},
    ]


def demo_reviews() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "review-1",
            "user_id": "user-1",
            "car_id": "car-1",
            "booking_id": "booking-2",
            "rating": 5,
            "comment": "Clean car and fast pickup.",
            "created_at": now - timedelta(days=2),
        }
    ]


def demo_payment_methods() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "_id": "payment-user-1-card-1",
            "user_id": "user-1",
            "type": "card",
            "brand": "Visa",
            "last4": "4242",
            "is_default": True,
            "created_at": now,
        }
    ]
